/*
 * The valumi wordmark, generated by tools/gen_logo.py: two 4-bit alpha masks
 * of logo_width x logo_height, packed two pixels a byte (high nibble first)
 * along rows with no padding -- the letters, and the star dotting the i.
 */
#pragma once

#include <stdint.h>

extern const int logo_width;
extern const int logo_height;
extern const uint8_t logo_text[];
extern const uint8_t logo_star[];
