#!/usr/bin/env python3
"""Rasterise a TTF into a 4-bit-alpha bitmap font as a C source file.

The output pairs with board_font.c in components/board_c6_lcd147: each glyph
is stored as rows of packed 4-bit coverage values (two pixels per byte, high
nibble first), which the renderer alpha-blends over the framebuffer.

Usage:
  gen_font.py <ttf> <px_size> <c_identifier> <output.c> [charset]

The default charset covers this project's needs: digits, uppercase, and the
punctuation a price ticker uses. Regenerate rather than hand-edit the output.
"""

import sys

from PIL import Image, ImageDraw, ImageFont

DEFAULT_CHARSET = " %+,-./0123456789:ABCDEFGHIJKLMNOPQRSTUVWXYZ"


def main() -> None:
    if len(sys.argv) < 5:
        sys.exit(__doc__)
    ttf_path, size, ident, out_path = sys.argv[1:5]
    charset = sys.argv[5] if len(sys.argv) > 5 else DEFAULT_CHARSET
    size = int(size)

    font = ImageFont.truetype(ttf_path, size)
    ascent, descent = font.getmetrics()
    line_height = ascent + descent

    bitmap = bytearray()
    glyphs = []  # (char, w, h, bearing_x, bearing_y, advance, offset)

    for ch in charset:
        # Render one glyph generously oversized, then crop to ink.
        pad = size
        img = Image.new("L", (size * 3, line_height + 2 * pad), 0)
        draw = ImageDraw.Draw(img)
        draw.text((pad, pad), ch, font=font, fill=255)
        advance = round(font.getlength(ch))

        bbox = img.getbbox()
        if bbox is None:  # space: no ink, advance only
            glyphs.append((ch, 0, 0, 0, 0, advance, len(bitmap)))
            continue

        x0, y0, x1, y1 = bbox
        img = img.crop(bbox)
        w, h = img.size
        bearing_x = x0 - pad
        bearing_y = y0 - pad  # ink top relative to the line's top

        offset = len(bitmap)
        px = img.load()
        for row in range(h):
            for col in range(0, w, 2):
                hi = px[col, row] >> 4
                lo = (px[col + 1, row] >> 4) if col + 1 < w else 0
                bitmap.append((hi << 4) | lo)
        glyphs.append((ch, w, h, bearing_x, bearing_y, advance, offset))

    with open(out_path, "w") as f:
        f.write("/* Generated by tools/gen_font.py -- do not edit.\n")
        f.write(f" * {size} px.\n */\n\n")
        f.write('#include "board_font.h"\n\n')

        f.write(f"static const uint8_t {ident}_bitmap[] = {{\n")
        for i in range(0, len(bitmap), 16):
            row = ", ".join(f"0x{b:02X}" for b in bitmap[i : i + 16])
            f.write(f"    {row},\n")
        f.write("};\n\n")

        f.write(f"static const board_glyph_t {ident}_glyphs[] = {{\n")
        for ch, w, h, bx, by, adv, off in glyphs:
            name = ch if ch != "\\" else "backslash"
            f.write(
                f"    {{{w}, {h}, {bx}, {by}, {adv}, {off}}}, /* '{name}' */\n"
            )
        f.write("};\n\n")

        cs = charset.replace("\\", "\\\\").replace('"', '\\"')
        f.write(f"const board_font_t {ident} = {{\n")
        f.write(f"    .bitmap = {ident}_bitmap,\n")
        f.write(f"    .glyphs = {ident}_glyphs,\n")
        f.write(f'    .charset = "{cs}",\n')
        f.write(f"    .line_height = {line_height},\n")
        f.write(f"    .baseline = {ascent},\n")
        f.write("};\n")

    total = len(bitmap) + len(glyphs) * 6
    print(f"{ident}: {len(glyphs)} glyphs, {total} bytes")


if __name__ == "__main__":
    main()
