/*
 * The on-screen font at three sizes, generated by tools/gen_font.py.
 * Regenerate with the commands in the README rather than editing.
 */
#pragma once

#include "board_font.h"

extern const board_font_t font_large;  /* 40 px: symbol + price line */
extern const board_font_t font_medium; /* 22 px: change line */
extern const board_font_t font_small;  /* 14 px: tags and overlays */
